STATUS_UNCONFIRMED = "unconfirmed"
STATUS_CONFIRMED = "confirmed"
STATUS_PENDING_ADJUSTMENT = "pending_adjustment"
STATUS_ADJUSTED = "adjusted"
STATUS_INCREASED = "increased"
STATUS_PARTIAL_REFUNDED = "partial_refunded"
STATUS_REFUNDED = "refunded"

ADJUSTMENT_TYPE_INCREASE = "increase"
ADJUSTMENT_TYPE_DECREASE = "decrease"
ADJUSTMENT_TYPE_EQUAL = "equal"

ADJUSTMENT_STATUS_PENDING = "pending"
ADJUSTMENT_STATUS_ADJUSTED = "adjusted"
ACCOMMODATION_STATUS_GENERATED = "generated"
ACCOMMODATION_STATUS_CONFIRMED = "confirmed"
ACCOMMODATION_STATUS_CANCELLED = "cancelled"

VALID_STATUSES = {
    STATUS_UNCONFIRMED,
    STATUS_CONFIRMED,
    STATUS_PENDING_ADJUSTMENT,
    STATUS_ADJUSTED,
    STATUS_INCREASED,
    STATUS_PARTIAL_REFUNDED,
    STATUS_REFUNDED,
}

VALID_ADJUSTMENT_TYPES = {
    ADJUSTMENT_TYPE_INCREASE,
    ADJUSTMENT_TYPE_DECREASE,
    ADJUSTMENT_TYPE_EQUAL,
}

VALID_ADJUSTMENT_STATUSES = {
    ADJUSTMENT_STATUS_PENDING,
    ADJUSTMENT_STATUS_ADJUSTED,
}

VALID_ACCOMMODATION_STATUSES = {
    ACCOMMODATION_STATUS_GENERATED,
    ACCOMMODATION_STATUS_CONFIRMED,
    ACCOMMODATION_STATUS_CANCELLED,
}

NON_EARLY_BIRD_VALID_UNTIL = "2026-12-31T23:59:59"

MESSAGE_STATUS_PENDING = "pending"
MESSAGE_STATUS_PROCESSING = "processing"
MESSAGE_STATUS_FAILED = "failed"
MESSAGE_STATUS_SUCCEEDED = "succeeded"
MESSAGE_STATUS_DEAD = "dead"

NOTIFICATION_TYPE_QUOTATION = "quotation"
NOTIFICATION_TYPE_PAYMENT = "payment"
NOTIFICATION_TYPE_ADJUSTMENT = "adjustment"
NOTIFICATION_TYPE_REFUND = "refund"
NOTIFICATION_TYPE_ACCOMMODATION = "accommodation"

VALID_NOTIFICATION_TYPES = {
    NOTIFICATION_TYPE_QUOTATION,
    NOTIFICATION_TYPE_PAYMENT,
    NOTIFICATION_TYPE_ADJUSTMENT,
    NOTIFICATION_TYPE_REFUND,
    NOTIFICATION_TYPE_ACCOMMODATION,
}
