STATUS_QUOTED = "quoted"
STATUS_PAID = "paid"
STATUS_REFUND_REQUESTED = "refund_requested"
STATUS_REFUNDED = "refunded"

VALID_STATUSES = {
    STATUS_QUOTED,
    STATUS_PAID,
    STATUS_REFUND_REQUESTED,
    STATUS_REFUNDED,
}

NON_EARLY_BIRD_VALID_UNTIL = "2026-12-31T23:59:59"

MESSAGE_STATUS_PENDING = "pending"
MESSAGE_STATUS_PROCESSING = "processing"
MESSAGE_STATUS_FAILED = "failed"
MESSAGE_STATUS_SUCCEEDED = "succeeded"
MESSAGE_STATUS_DEAD = "dead"

NOTIFICATION_TYPE_QUOTATION = "quotation"
NOTIFICATION_TYPE_PAYMENT = "payment"
NOTIFICATION_TYPE_ADJUSTMENT = "adjustment"
NOTIFICATION_TYPE_REFUND = "refund"

VALID_NOTIFICATION_TYPES = {
    NOTIFICATION_TYPE_QUOTATION,
    NOTIFICATION_TYPE_PAYMENT,
    NOTIFICATION_TYPE_ADJUSTMENT,
    NOTIFICATION_TYPE_REFUND,
}
