STATUS_QUOTED = "quoted"
STATUS_PAID = "paid"
STATUS_REFUND_REQUESTED = "refund_requested"
STATUS_REFUNDED = "refunded"

VALID_STATUSES = {
    STATUS_QUOTED,
    STATUS_PAID,
    STATUS_REFUND_REQUESTED,
    STATUS_REFUNDED,
}

NON_EARLY_BIRD_VALID_UNTIL = "2026-12-31T23:59:59"
